FROM node:buster-slim

RUN apt-get update && \
    apt-get -y install git unzip mono-runtime wget && \
    apt-get clean

# Inklecate flatpak version and checksum
ENV INKLECATE_VERSION 0.9.0
ENV INKLECATE_CHECKSUM c2d9d042f15379730c93a2af0807534d11bc1ff22e5e99a5f9c216d1c15db8da
ENV INKLECATE_URL https://github.com/inkle/ink/releases/download/${INKLECATE_VERSION}/inklecate_windows_and_linux.zip
RUN mkdir /ink
RUN wget -q -O /ink/inklecate.zip ${INKLECATE_URL} && \
    echo "${INKLECATE_CHECKSUM} /ink/inklecate.zip" | sha256sum -c && \
    cd /ink && unzip inklecate.zip && rm -f inklecate.zip && \
    (echo '#!/bin/bash'; echo 'mono /ink/inklecate.exe $@') > /bin/inklecate && \
    chmod a+x /bin/inklecate
